# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6015a87c041e6ef463b1126006733778b8e2680c63e7e3f632b493b75a791809a8c4d55644420f324e8e1ee50ebb3c538d985f6af4c7ebdbbeec7969f09cebc9

test:
  secret_key_base: ebe896a3b051549c9c8f0855d91d09bb18bf87ed1e8cb85655602aba2cd12e2b82669b3ca107c5eeb7788093b9ac9096cb5354c4037f17fab8b1f9ae1ab15675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
